from app.rag.conversational_buffer import buffer_memory
import json

memory = buffer_memory()

def evaluate_answer_quality(test_data, rag_chain, retriever, llm):

    total_score = 0
    total_questions = len(test_data)

    for item in test_data:

        question = item["question"]

        
        history = memory.load_memory_variables({})["chat_history"]

        docs = retriever.invoke(question)

        context = "\n".join([
            doc.page_content for doc in docs
        ])

        ans = rag_chain.invoke({
            "context": context,
            "question": question,
            "chat_history": history
        })

        prompt = f"""
You are an AI evaluator.

Your job is to evaluate the quality of an answer generated by a Retrieval-Augmented Generation (RAG) system.

Evaluate the answer using the following criteria:

1. Correctness – Is the answer factually correct based on the provided context?
2. Completeness – Does the answer fully address the user's question?
3. Relevance – Is the answer relevant to the user's current question and the conversation history?

Chat History:
{history}

Current Question:
{question}

Retrieved Context:
{context}

Ground Truth Answer:
{item['ground_truth_answer']}

Generated Answer:
{ans}

Instructions:
Score the answer quality from 1 to 5.

Scoring Guide:
5 = Excellent (correct, complete, and fully relevant)
4 = Good (mostly correct with minor issues)
3 = Partially correct or incomplete
2 = Mostly incorrect
1 = Completely incorrect

Return only JSON in this format:

{{
 "score": number,
 "reason": "short explanation"
}}
"""

        result = llm.invoke(prompt).content

        try:
            parsed = json.loads(result)
            score = parsed["score"]
        except:
            score = 0

        total_score += score

    answer_quality = total_score / total_questions if total_questions > 0 else 0

    return total_score, answer_quality