load_test_data=[
  {"question": "What is Artificial Intelligence?", "ground_truth_answer": "Artificial Intelligence is the simulation of human intelligence in machines.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What are the main subfields of AI?", "ground_truth_answer": "Machine learning, natural language processing, and computer vision.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "Where is AI widely used?", "ground_truth_answer": "AI is used in chatbots, recommendation systems, autonomous vehicles, and healthcare.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What are Large Language Models?", "ground_truth_answer": "Large Language Models are AI systems trained on vast amounts of text data.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What does machine learning belong to?", "ground_truth_answer": "Machine learning is a subfield of Artificial Intelligence.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What does NLP stand for?", "ground_truth_answer": "Natural Language Processing.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What field enables AI to understand images?", "ground_truth_answer": "Computer vision.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "AI systems simulate what type of intelligence?", "ground_truth_answer": "Human intelligence.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "Name one healthcare application of AI.", "ground_truth_answer": "AI is used in healthcare applications.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What type of vehicles use AI?", "ground_truth_answer": "Autonomous vehicles use AI.", "expected_source": "Artificial_Intelligence.pdf"},

  {"question": "What is climate change?", "ground_truth_answer": "Climate change refers to long-term changes in temperature and weather patterns.", "expected_source": "Climate_Change.pdf"},
  {"question": "What mainly drives climate change?", "ground_truth_answer": "Human activities such as burning fossil fuels and deforestation.", "expected_source": "Climate_Change.pdf"},
  {"question": "What are the effects of climate change?", "ground_truth_answer": "Rising sea levels, extreme weather events, and biodiversity loss.", "expected_source": "Climate_Change.pdf"},
  {"question": "What causes rising sea levels?", "ground_truth_answer": "Climate change causes rising sea levels.", "expected_source": "Climate_Change.pdf"},
  {"question": "What type of events increase due to climate change?", "ground_truth_answer": "Extreme weather events.", "expected_source": "Climate_Change.pdf"},
  {"question": "What happens to biodiversity due to climate change?", "ground_truth_answer": "Biodiversity loss occurs.", "expected_source": "Climate_Change.pdf"},
  {"question": "Name one mitigation strategy for climate change.", "ground_truth_answer": "Renewable energy adoption.", "expected_source": "Climate_Change.pdf"},
  {"question": "What should be reduced to fight climate change?", "ground_truth_answer": "Carbon emissions should be reduced.", "expected_source": "Climate_Change.pdf"},
  {"question": "Deforestation contributes to what problem?", "ground_truth_answer": "Deforestation contributes to climate change.", "expected_source": "Climate_Change.pdf"},
  {"question": "Burning fossil fuels leads to what issue?", "ground_truth_answer": "Burning fossil fuels drives climate change.", "expected_source": "Climate_Change.pdf"},

  {"question": "What is blockchain?", "ground_truth_answer": "Blockchain is a distributed ledger technology that records transactions across multiple computers.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What does blockchain ensure?", "ground_truth_answer": "Transparency, security, and immutability of data.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What is blockchain widely used for?", "ground_truth_answer": "Cryptocurrencies like Bitcoin.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "Name one cryptocurrency using blockchain.", "ground_truth_answer": "Bitcoin.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "Is blockchain centralized or distributed?", "ground_truth_answer": "Blockchain is distributed.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "How does blockchain improve security?", "ground_truth_answer": "Through transparency and immutability.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What other industry uses blockchain besides crypto?", "ground_truth_answer": "Supply chain management.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "How is blockchain used in identity systems?", "ground_truth_answer": "It is used for digital identity verification.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What type of ledger is blockchain?", "ground_truth_answer": "A distributed ledger.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "Why is blockchain considered immutable?", "ground_truth_answer": "Because data cannot be easily altered once recorded.", "expected_source": "Blockchain_Technology.pdf"},

  {"question": "What is space exploration?", "ground_truth_answer": "Space exploration is the investigation of outer space using astronomy and space technology.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What was a major milestone in space exploration?", "ground_truth_answer": "The Moon landing.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What planet do Mars rovers explore?", "ground_truth_answer": "Mars.", "expected_source": "Space_Exploration.pdf"},
  {"question": "Which organization plays a major role in space exploration?", "ground_truth_answer": "NASA.", "expected_source": "Space_Exploration.pdf"},
  {"question": "Name a private company involved in space exploration.", "ground_truth_answer": "SpaceX.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What is a goal of future missions?", "ground_truth_answer": "Mars colonization.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What does astronomy help study?", "ground_truth_answer": "Outer space.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What technology is used for space investigation?", "ground_truth_answer": "Space technology.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What was explored by Apollo missions?", "ground_truth_answer": "The Moon.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What is deep space exploration focused on?", "ground_truth_answer": "Exploring regions beyond Earth and Mars.", "expected_source": "Space_Exploration.pdf"},

  {"question": "Which AI subfield processes language?", "ground_truth_answer": "Natural Language Processing.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What technology secures Bitcoin?", "ground_truth_answer": "Blockchain technology.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What causes biodiversity loss?", "ground_truth_answer": "Climate change.", "expected_source": "Climate_Change.pdf"},
  {"question": "Which company is linked with Mars missions?", "ground_truth_answer": "SpaceX.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What enables chatbots to work?", "ground_truth_answer": "Artificial Intelligence.", "expected_source": "Artificial_Intelligence.pdf"},
  {"question": "What is reduced to mitigate climate change?", "ground_truth_answer": "Carbon emissions.", "expected_source": "Climate_Change.pdf"},
  {"question": "What makes blockchain transparent?", "ground_truth_answer": "Its distributed ledger system.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What field studies stars and planets?", "ground_truth_answer": "Astronomy.", "expected_source": "Space_Exploration.pdf"},
  {"question": "What records transactions across computers?", "ground_truth_answer": "Blockchain.", "expected_source": "Blockchain_Technology.pdf"},
  {"question": "What allows AI to recognize patterns in data?", "ground_truth_answer": "Machine learning.", "expected_source": "Artificial_Intelligence.pdf"}
]