import json
from app.rag.conversational_buffer import buffer_memory
from app.llm import get_llm
memory = buffer_memory()
llm = get_llm()

def evaluate_answer_quality(question, answer, context):

    history = memory.load_memory_variables({})["chat_history"]

    prompt = f"""
You are an AI evaluator.

Your job is to evaluate the quality of an answer generated by a Retrieval-Augmented Generation (RAG) system.

Evaluate the answer using the following criteria:

1. Correctness – Is the answer factually correct based on the provided context?
2. Completeness – Does the answer fully address the user's question?
3. Relevance – Is the answer relevant to the user's current question and the conversation history?

Chat History:
{history}

Current Question:
{question}

Retrieved Context:
{context}

Generated Answer:
{answer}

Instructions:
Score the answer quality from 1 to 5.

Scoring Guide:
5 = Excellent (correct, complete, and fully relevant)
4 = Good (mostly correct with minor issues)
3 = Partially correct or incomplete
2 = Mostly incorrect
1 = Completely incorrect

Return only JSON in this format:

{{
 "score": number,
 "reason": "short explanation"
}}
"""

    result = llm.invoke(prompt).content

    try:
        parsed = json.loads(result)
        score = parsed["score"]
        reason = parsed["reason"]
    except:
        score = 0
        reason = "evaluation failed"

    return score, reason